[project]
name = "sku-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.76.0",
    "pandas>=2.2.3",
    "polars>=1.28.1",
]
